server:
  servlet:
    context-path: /cleonora/admin
  port: 8081


spring:


  application:
    name: Cleonora

  datasource:
    url: jdbc:postgresql://cleonora-db:5432/postgres
    username: postgres
    password: "0000"

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: cleonora_database
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

secret-key: ${SENDGRID_API_KEY}
sender: "dima.ivanov@avada-media.com"

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    file: INFO
  file:
    name: "/home/slj/projects/Cleonora-R.Miahkykh/logs/CleonoraDocker.log"

upload:
  folder:
    path: "/home/slj/projects/Cleonora-R.Miahkykh/uploads"



work-schedule:
  schedule:
    monday:
      start: "08:00"
      end: "18:00"
      lunch:
        start: "12:00"
        end: "13:00"
    tuesday:
      start: "08:00"
      end: "18:00"
      lunch:
        start: "12:00"
        end: "13:00"
    wednesday:
      start: "08:00"
      end: "18:00"
      lunch:
        start: "12:00"
        end: "13:00"
    thursday:
      start: "08:00"
      end: "18:00"
      lunch:
        start: "12:00"
        end: "13:00"
    friday:
      start: "08:00"
      end: "18:00"
      lunch:
        start: "12:00"
        end: "13:00"
    saturday:
      start: "10:00"
      end: "14:00"
      lunch:
        start: "12:00"
        end: "12:30"
    sunday:
      start: "off"
